version: 0.1.{build}
branches:
  only:
  - master
configuration: Release
build:
  verbosity: minimal
test: off
notifications:
- provider: Email
  to:
  - tbenfield@standpointtech.com
  subject: Mailgun.NET Build
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true